# Generated by Django 5.2.7 on 2025-10-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='馬名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='レース名')),
                ('held_date', models.DateField(verbose_name='開催日')),
                ('stake_per_unit', models.PositiveIntegerField(default=100, verbose_name='一口当たりの掛け金')),
                ('status', models.CharField(choices=[('PREP', '準備中'), ('OPEN', '受付中'), ('CLOSED', '受付終了'), ('FIN', 'レース終了')], default='PREP', max_length=10, verbose_name='ステータス')),
                ('horses', models.ManyToManyField(to='race.horse', verbose_name='出走馬')),
            ],
        ),
        migrations.CreateModel(
            name='InitialOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('WIN', '単勝'), ('TRI', '3連単'), ('TRO', '3連複')], max_length=3, verbose_name='賭け式')),
                ('odds', models.FloatField(verbose_name='オッズ')),
                ('horse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_horse1', to='race.horse')),
                ('horse2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odds_horse2', to='race.horse')),
                ('horse3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odds_horse3', to='race.horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race', verbose_name='レース')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('WIN', '単勝'), ('TRI', '3連単'), ('TRO', '3連複')], max_length=3, verbose_name='賭け式')),
                ('units', models.PositiveIntegerField(verbose_name='口数')),
                ('horse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_horse1', to='race.horse')),
                ('horse2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_horse2', to='race.horse')),
                ('horse3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_horse3', to='race.horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race', verbose_name='レース')),
            ],
        ),
    ]
