# Generated by Django 5.2.7 on 2025-10-06 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bettor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='投票者名')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='bettor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='race.bettor', verbose_name='投票者'),
        ),
    ]
