# Generated by Django 5.2.7 on 2025-10-06 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_bettor_bet_bettor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bettor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='race.bettor', verbose_name='投票者'),
            preserve_default=False,
        ),
    ]
